// <auto-generated />
using System;
using GreenGo.DB.API.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace GreenGo.DB.API.Migrations
{
    [DbContext(typeof(PanelsContext))]
    [Migration("20201217203247_Revives")]
    partial class Revives
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("GreenGo.DB.API.Entities.Inverter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Company");

                    b.Property<double>("Power");

                    b.Property<double>("Price");

                    b.HasKey("Id");

                    b.ToTable("Inverters");

                    b.HasData(
                        new { Id = new Guid("5acd3baf-4d4e-4cfe-8450-e5638d211ab9"), Power = 0.0, Price = 0.0 },
                        new { Id = new Guid("4f3e3588-db78-4c65-b3b4-75d33dbb9205"), Power = 0.0, Price = 0.0 }
                    );
                });

            modelBuilder.Entity("GreenGo.DB.API.Entities.Panel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Company")
                        .IsRequired();

                    b.Property<double>("Power");

                    b.Property<double>("Price");

                    b.Property<double>("height");

                    b.Property<double>("width");

                    b.HasKey("Id");

                    b.ToTable("Panels");

                    b.HasData(
                        new { Id = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"), Company = "Green Life", Power = 45.0, Price = 4500.0, height = 40.0, width = 50.0 },
                        new { Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba96"), Company = "Yellow Life", Power = 60.0, Price = 7500.0, height = 50.0, width = 50.0 },
                        new { Id = new Guid("2902b665-1190-4c70-9915-b9c2d7680450"), Company = "Blue Life", Power = 70.0, Price = 9500.0, height = 60.0, width = 60.0 },
                        new { Id = new Guid("102b566b-ba1f-404c-b2df-e2cde39ade09"), Company = "Violet Life", Power = 100.0, Price = 10500.0, height = 90.0, width = 80.0 }
                    );
                });

            modelBuilder.Entity("GreenGo.DB.API.Entities.ReferenceTables", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("IdInverter");

                    b.Property<Guid>("IdStation");

                    b.HasKey("Id");

                    b.ToTable("ReferenceTables");

                    b.HasData(
                        new { Id = new Guid("f4e832fe-5d7b-47e1-be35-fd4178172a19"), IdInverter = new Guid("32fb5677-bda8-47a2-a29c-2a0220cd3eda"), IdStation = new Guid("04f942e4-ff81-4f24-af35-58f77c0fd2c6") }
                    );
                });

            modelBuilder.Entity("GreenGo.DB.API.Entities.SolarStation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("SolarStations");

                    b.HasData(
                        new { Id = new Guid("85ec08dc-6245-44ef-9ce7-9829596ef939") }
                    );
                });

            modelBuilder.Entity("GreenGo.DB.API.Entities.WindTurbine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Company");

                    b.Property<double>("Diameter");

                    b.Property<string>("Matherial");

                    b.Property<double>("Price");

                    b.Property<double>("defPower");

                    b.Property<int>("numBlades");

                    b.HasKey("Id");

                    b.ToTable("WindTurbines");
                });
#pragma warning restore 612, 618
        }
    }
}
