// <auto-generated />
using System;
using GreenGo.DB.API.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace GreenGo.DB.API.Migrations
{
    [DbContext(typeof(PanelsContext))]
    [Migration("20201217203322_Renasance")]
    partial class Renasance
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("GreenGo.DB.API.Entities.Inverter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Company");

                    b.Property<double>("Power");

                    b.Property<double>("Price");

                    b.HasKey("Id");

                    b.ToTable("Inverters");

                    b.HasData(
                        new { Id = new Guid("127657a5-eacc-4fbc-bc9a-ebf3b19be76b"), Power = 0.0, Price = 0.0 },
                        new { Id = new Guid("ca31fd21-68ba-4784-9a70-35fe76876a73"), Power = 0.0, Price = 0.0 }
                    );
                });

            modelBuilder.Entity("GreenGo.DB.API.Entities.Panel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Company")
                        .IsRequired();

                    b.Property<double>("Power");

                    b.Property<double>("Price");

                    b.Property<double>("height");

                    b.Property<double>("width");

                    b.HasKey("Id");

                    b.ToTable("Panels");

                    b.HasData(
                        new { Id = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"), Company = "Green Life", Power = 45.0, Price = 4500.0, height = 40.0, width = 50.0 },
                        new { Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba96"), Company = "Yellow Life", Power = 60.0, Price = 7500.0, height = 50.0, width = 50.0 },
                        new { Id = new Guid("2902b665-1190-4c70-9915-b9c2d7680450"), Company = "Blue Life", Power = 70.0, Price = 9500.0, height = 60.0, width = 60.0 },
                        new { Id = new Guid("102b566b-ba1f-404c-b2df-e2cde39ade09"), Company = "Violet Life", Power = 100.0, Price = 10500.0, height = 90.0, width = 80.0 }
                    );
                });

            modelBuilder.Entity("GreenGo.DB.API.Entities.ReferenceTables", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("IdInverter");

                    b.Property<Guid>("IdStation");

                    b.HasKey("Id");

                    b.ToTable("ReferenceTables");

                    b.HasData(
                        new { Id = new Guid("a8f6895f-d455-438d-beda-93538c597aca"), IdInverter = new Guid("753fdc73-7f9f-4f4f-bd57-031de0a9ee2b"), IdStation = new Guid("1640da65-06e5-491a-8aec-86f5b62538c2") }
                    );
                });

            modelBuilder.Entity("GreenGo.DB.API.Entities.SolarStation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("SolarStations");

                    b.HasData(
                        new { Id = new Guid("d5b18e89-0b44-4132-93f5-0e5276eb2c88") }
                    );
                });

            modelBuilder.Entity("GreenGo.DB.API.Entities.WindTurbine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Company");

                    b.Property<double>("Diameter");

                    b.Property<string>("Matherial");

                    b.Property<double>("Price");

                    b.Property<double>("defPower");

                    b.Property<int>("numBlades");

                    b.HasKey("Id");

                    b.ToTable("WindTurbines");
                });
#pragma warning restore 612, 618
        }
    }
}
